version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:blue'

    [blocks.segments.properties]
      style = 'full'
    
    [[blocks.segments]]
      type = 'text'
      style = 'plain'
      background = 'transparent'
      foreground = 'white'
      template = '>'

[palette]
blue = '#7CB0FF'
